// <auto-generated />
namespace _2_CodeFirstApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class createMig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createMig));
        
        string IMigrationMetadata.Id
        {
            get { return "202304050843185_createMig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
