// <auto-generated />
namespace _3_SahibindenApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Sahibinden : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sahibinden));
        
        string IMigrationMetadata.Id
        {
            get { return "202304060918171_Sahibinden"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
